// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});

// Clear invalid sessions on startup
supabase.auth.onAuthStateChange(async (event, session) => {
  console.log('🔐 Auth state changed:', event, session ? 'Session exists' : 'No session');
  
  if (event === 'TOKEN_REFRESHED' && !session) {
    console.log('⚠️ Session refresh failed, clearing storage');
    localStorage.removeItem('supabase.auth.token');
    sessionStorage.clear();
  }
  
  // Verificar se o token JWT é válido
  if (session && session.access_token) {
    try {
      // Tentar verificar a validade do token
      const { data, error } = await supabase.auth.getUser();
      if (error || !data.user) {
        console.log('❌ Invalid JWT token detected, clearing session');
        localStorage.removeItem('supabase.auth.token');
        sessionStorage.clear();
        await supabase.auth.signOut();
      }
    } catch (error) {
      console.error('❌ Error validating token:', error);
      localStorage.removeItem('supabase.auth.token');
      sessionStorage.clear();
    }
  }
});